export const ERROR_CODES = {
  // Authentication
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_INSUFFICIENT_PERMISSIONS: 'AUTH_INSUFFICIENT_PERMISSIONS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_NOT_AUTHENTICATED: 'AUTH_NOT_AUTHENTICATED',

  // Validation
  VAL_REQUIRED_FIELD: 'VAL_REQUIRED_FIELD',
  VAL_INVALID_FORMAT: 'VAL_INVALID_FORMAT',
  VAL_INVALID_EMAIL: 'VAL_INVALID_EMAIL',
  VAL_PASSWORD_TOO_WEAK: 'VAL_PASSWORD_TOO_WEAK',

  // Business Logic
  BIZ_LIMIT_EXCEEDED: 'BIZ_LIMIT_EXCEEDED',
  BIZ_DUPLICATE_ENTRY: 'BIZ_DUPLICATE_ENTRY',
  BIZ_NOT_FOUND: 'BIZ_NOT_FOUND',
  BIZ_INVALID_STATE: 'BIZ_INVALID_STATE',
  BIZ_PAYMENT_FAILED: 'BIZ_PAYMENT_FAILED',

  // System
  SYS_SERVER_ERROR: 'SYS_SERVER_ERROR',
  SYS_RATE_LIMIT: 'SYS_RATE_LIMIT',
  SYS_CONFIG_ERROR: 'SYS_CONFIG_ERROR',
  SYS_TOKEN_REFRESH_FAILED: 'SYS_TOKEN_REFRESH_FAILED',
  SYS_TOKEN_INVALID: 'SYS_TOKEN_INVALID',
  SYS_TOKEN_PERSISTENCE_FAILED: 'SYS_TOKEN_PERSISTENCE_FAILED',
  SYS_INTERNAL_ERROR: 'SYS_INTERNAL_ERROR',

  // Network
  NET_CONNECTION_ERROR: 'NET_CONNECTION_ERROR',
  NET_TIMEOUT: 'NET_TIMEOUT',
} as const

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES]

// Helper to check if a string is a valid error code
export function isErrorCode(code: string): code is ErrorCode {
  return Object.values(ERROR_CODES).includes(code as ErrorCode)
}
