/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as Oauth2AccessCodeRouteImport } from './routes/oauth2/accessCode'
import { Route as InviteInvitationIdRouteImport } from './routes/invite.$invitationId'
import { Route as BookFormIdRouteImport } from './routes/book.$formId'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSuperadminRouteImport } from './routes/_authenticated/superadmin'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSelectOrganizationRouteImport } from './routes/_authenticated/select-organization'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedFormsRouteImport } from './routes/_authenticated/forms'
import { Route as AuthenticatedBookingsRouteImport } from './routes/_authenticated/bookings'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedSuperadminIndexRouteImport } from './routes/_authenticated/superadmin/index'
import { Route as AuthenticatedSuperadminWorkspacesRouteImport } from './routes/_authenticated/superadmin/workspaces'
import { Route as AuthenticatedSuperadminUsersRouteImport } from './routes/_authenticated/superadmin/users'
import { Route as AuthenticatedTodosIdEditRouteImport } from './routes/_authenticated/todos.$id.edit'
import { Route as AuthenticatedFormFormIdEditRouteImport } from './routes/_authenticated/form.$formId.edit'
import { ServerRoute as ApiHealthServerRouteImport } from './routes/api/health'
import { ServerRoute as ApiStripeWebhookServerRouteImport } from './routes/api/stripe/webhook'
import { ServerRoute as ApiAvatarsUploadServerRouteImport } from './routes/api/avatars/upload'
import { ServerRoute as ApiAvatarsDeleteServerRouteImport } from './routes/api/avatars/delete'
import { ServerRoute as ApiAvatarsSplatServerRouteImport } from './routes/api/avatars/$'
import { ServerRoute as ApiAuthSplatServerRouteImport } from './routes/api/auth/$'

const rootServerRouteImport = createServerRootRoute()

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const Oauth2AccessCodeRoute = Oauth2AccessCodeRouteImport.update({
  id: '/oauth2/accessCode',
  path: '/oauth2/accessCode',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInvitationIdRoute = InviteInvitationIdRouteImport.update({
  id: '/invite/$invitationId',
  path: '/invite/$invitationId',
  getParentRoute: () => rootRouteImport,
} as any)
const BookFormIdRoute = BookFormIdRouteImport.update({
  id: '/book/$formId',
  path: '/book/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/auth/signin',
  path: '/auth/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperadminRoute = AuthenticatedSuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSelectOrganizationRoute =
  AuthenticatedSelectOrganizationRouteImport.update({
    id: '/select-organization',
    path: '/select-organization',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormsRoute = AuthenticatedFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookingsRoute = AuthenticatedBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuperadminIndexRoute =
  AuthenticatedSuperadminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const AuthenticatedSuperadminWorkspacesRoute =
  AuthenticatedSuperadminWorkspacesRouteImport.update({
    id: '/workspaces',
    path: '/workspaces',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const AuthenticatedSuperadminUsersRoute =
  AuthenticatedSuperadminUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSuperadminRoute,
  } as any)
const AuthenticatedTodosIdEditRoute =
  AuthenticatedTodosIdEditRouteImport.update({
    id: '/todos/$id/edit',
    path: '/todos/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFormFormIdEditRoute =
  AuthenticatedFormFormIdEditRouteImport.update({
    id: '/form/$formId/edit',
    path: '/form/$formId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiHealthServerRoute = ApiHealthServerRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiStripeWebhookServerRoute = ApiStripeWebhookServerRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAvatarsUploadServerRoute = ApiAvatarsUploadServerRouteImport.update({
  id: '/api/avatars/upload',
  path: '/api/avatars/upload',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAvatarsDeleteServerRoute = ApiAvatarsDeleteServerRouteImport.update({
  id: '/api/avatars/delete',
  path: '/api/avatars/delete',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAvatarsSplatServerRoute = ApiAvatarsSplatServerRouteImport.update({
  id: '/api/avatars/$',
  path: '/api/avatars/$',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiAuthSplatServerRoute = ApiAuthSplatServerRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootServerRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/billing': typeof AuthenticatedBillingRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/select-organization': typeof AuthenticatedSelectOrganizationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/superadmin': typeof AuthenticatedSuperadminRouteWithChildren
  '/team': typeof AuthenticatedTeamRoute
  '/auth/signin': typeof AuthSigninRoute
  '/book/$formId': typeof BookFormIdRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/oauth2/accessCode': typeof Oauth2AccessCodeRoute
  '/': typeof AuthenticatedIndexRoute
  '/superadmin/users': typeof AuthenticatedSuperadminUsersRoute
  '/superadmin/workspaces': typeof AuthenticatedSuperadminWorkspacesRoute
  '/superadmin/': typeof AuthenticatedSuperadminIndexRoute
  '/form/$formId/edit': typeof AuthenticatedFormFormIdEditRoute
  '/todos/$id/edit': typeof AuthenticatedTodosIdEditRoute
}
export interface FileRoutesByTo {
  '/billing': typeof AuthenticatedBillingRoute
  '/bookings': typeof AuthenticatedBookingsRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/select-organization': typeof AuthenticatedSelectOrganizationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/team': typeof AuthenticatedTeamRoute
  '/auth/signin': typeof AuthSigninRoute
  '/book/$formId': typeof BookFormIdRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/oauth2/accessCode': typeof Oauth2AccessCodeRoute
  '/': typeof AuthenticatedIndexRoute
  '/superadmin/users': typeof AuthenticatedSuperadminUsersRoute
  '/superadmin/workspaces': typeof AuthenticatedSuperadminWorkspacesRoute
  '/superadmin': typeof AuthenticatedSuperadminIndexRoute
  '/form/$formId/edit': typeof AuthenticatedFormFormIdEditRoute
  '/todos/$id/edit': typeof AuthenticatedTodosIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/bookings': typeof AuthenticatedBookingsRoute
  '/_authenticated/forms': typeof AuthenticatedFormsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/select-organization': typeof AuthenticatedSelectOrganizationRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/superadmin': typeof AuthenticatedSuperadminRouteWithChildren
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/auth/signin': typeof AuthSigninRoute
  '/book/$formId': typeof BookFormIdRoute
  '/invite/$invitationId': typeof InviteInvitationIdRoute
  '/oauth2/accessCode': typeof Oauth2AccessCodeRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/superadmin/users': typeof AuthenticatedSuperadminUsersRoute
  '/_authenticated/superadmin/workspaces': typeof AuthenticatedSuperadminWorkspacesRoute
  '/_authenticated/superadmin/': typeof AuthenticatedSuperadminIndexRoute
  '/_authenticated/form/$formId/edit': typeof AuthenticatedFormFormIdEditRoute
  '/_authenticated/todos/$id/edit': typeof AuthenticatedTodosIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/billing'
    | '/bookings'
    | '/forms'
    | '/onboarding'
    | '/profile'
    | '/select-organization'
    | '/settings'
    | '/superadmin'
    | '/team'
    | '/auth/signin'
    | '/book/$formId'
    | '/invite/$invitationId'
    | '/oauth2/accessCode'
    | '/'
    | '/superadmin/users'
    | '/superadmin/workspaces'
    | '/superadmin/'
    | '/form/$formId/edit'
    | '/todos/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/billing'
    | '/bookings'
    | '/forms'
    | '/onboarding'
    | '/profile'
    | '/select-organization'
    | '/settings'
    | '/team'
    | '/auth/signin'
    | '/book/$formId'
    | '/invite/$invitationId'
    | '/oauth2/accessCode'
    | '/'
    | '/superadmin/users'
    | '/superadmin/workspaces'
    | '/superadmin'
    | '/form/$formId/edit'
    | '/todos/$id/edit'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/billing'
    | '/_authenticated/bookings'
    | '/_authenticated/forms'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/select-organization'
    | '/_authenticated/settings'
    | '/_authenticated/superadmin'
    | '/_authenticated/team'
    | '/auth/signin'
    | '/book/$formId'
    | '/invite/$invitationId'
    | '/oauth2/accessCode'
    | '/_authenticated/'
    | '/_authenticated/superadmin/users'
    | '/_authenticated/superadmin/workspaces'
    | '/_authenticated/superadmin/'
    | '/_authenticated/form/$formId/edit'
    | '/_authenticated/todos/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthSigninRoute: typeof AuthSigninRoute
  BookFormIdRoute: typeof BookFormIdRoute
  InviteInvitationIdRoute: typeof InviteInvitationIdRoute
  Oauth2AccessCodeRoute: typeof Oauth2AccessCodeRoute
}
export interface FileServerRoutesByFullPath {
  '/api/health': typeof ApiHealthServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/avatars/$': typeof ApiAvatarsSplatServerRoute
  '/api/avatars/delete': typeof ApiAvatarsDeleteServerRoute
  '/api/avatars/upload': typeof ApiAvatarsUploadServerRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookServerRoute
}
export interface FileServerRoutesByTo {
  '/api/health': typeof ApiHealthServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/avatars/$': typeof ApiAvatarsSplatServerRoute
  '/api/avatars/delete': typeof ApiAvatarsDeleteServerRoute
  '/api/avatars/upload': typeof ApiAvatarsUploadServerRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/health': typeof ApiHealthServerRoute
  '/api/auth/$': typeof ApiAuthSplatServerRoute
  '/api/avatars/$': typeof ApiAvatarsSplatServerRoute
  '/api/avatars/delete': typeof ApiAvatarsDeleteServerRoute
  '/api/avatars/upload': typeof ApiAvatarsUploadServerRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/health'
    | '/api/auth/$'
    | '/api/avatars/$'
    | '/api/avatars/delete'
    | '/api/avatars/upload'
    | '/api/stripe/webhook'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/health'
    | '/api/auth/$'
    | '/api/avatars/$'
    | '/api/avatars/delete'
    | '/api/avatars/upload'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/api/health'
    | '/api/auth/$'
    | '/api/avatars/$'
    | '/api/avatars/delete'
    | '/api/avatars/upload'
    | '/api/stripe/webhook'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiHealthServerRoute: typeof ApiHealthServerRoute
  ApiAuthSplatServerRoute: typeof ApiAuthSplatServerRoute
  ApiAvatarsSplatServerRoute: typeof ApiAvatarsSplatServerRoute
  ApiAvatarsDeleteServerRoute: typeof ApiAvatarsDeleteServerRoute
  ApiAvatarsUploadServerRoute: typeof ApiAvatarsUploadServerRoute
  ApiStripeWebhookServerRoute: typeof ApiStripeWebhookServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/oauth2/accessCode': {
      id: '/oauth2/accessCode'
      path: '/oauth2/accessCode'
      fullPath: '/oauth2/accessCode'
      preLoaderRoute: typeof Oauth2AccessCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$invitationId': {
      id: '/invite/$invitationId'
      path: '/invite/$invitationId'
      fullPath: '/invite/$invitationId'
      preLoaderRoute: typeof InviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$formId': {
      id: '/book/$formId'
      path: '/book/$formId'
      fullPath: '/book/$formId'
      preLoaderRoute: typeof BookFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/superadmin': {
      id: '/_authenticated/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof AuthenticatedSuperadminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/select-organization': {
      id: '/_authenticated/select-organization'
      path: '/select-organization'
      fullPath: '/select-organization'
      preLoaderRoute: typeof AuthenticatedSelectOrganizationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms': {
      id: '/_authenticated/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AuthenticatedFormsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookings': {
      id: '/_authenticated/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof AuthenticatedBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/superadmin/': {
      id: '/_authenticated/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof AuthenticatedSuperadminIndexRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/_authenticated/superadmin/workspaces': {
      id: '/_authenticated/superadmin/workspaces'
      path: '/workspaces'
      fullPath: '/superadmin/workspaces'
      preLoaderRoute: typeof AuthenticatedSuperadminWorkspacesRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/_authenticated/superadmin/users': {
      id: '/_authenticated/superadmin/users'
      path: '/users'
      fullPath: '/superadmin/users'
      preLoaderRoute: typeof AuthenticatedSuperadminUsersRouteImport
      parentRoute: typeof AuthenticatedSuperadminRoute
    }
    '/_authenticated/todos/$id/edit': {
      id: '/_authenticated/todos/$id/edit'
      path: '/todos/$id/edit'
      fullPath: '/todos/$id/edit'
      preLoaderRoute: typeof AuthenticatedTodosIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/form/$formId/edit': {
      id: '/_authenticated/form/$formId/edit'
      path: '/form/$formId/edit'
      fullPath: '/form/$formId/edit'
      preLoaderRoute: typeof AuthenticatedFormFormIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/avatars/upload': {
      id: '/api/avatars/upload'
      path: '/api/avatars/upload'
      fullPath: '/api/avatars/upload'
      preLoaderRoute: typeof ApiAvatarsUploadServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/avatars/delete': {
      id: '/api/avatars/delete'
      path: '/api/avatars/delete'
      fullPath: '/api/avatars/delete'
      preLoaderRoute: typeof ApiAvatarsDeleteServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/avatars/$': {
      id: '/api/avatars/$'
      path: '/api/avatars/$'
      fullPath: '/api/avatars/$'
      preLoaderRoute: typeof ApiAvatarsSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
  }
}

interface AuthenticatedSuperadminRouteChildren {
  AuthenticatedSuperadminUsersRoute: typeof AuthenticatedSuperadminUsersRoute
  AuthenticatedSuperadminWorkspacesRoute: typeof AuthenticatedSuperadminWorkspacesRoute
  AuthenticatedSuperadminIndexRoute: typeof AuthenticatedSuperadminIndexRoute
}

const AuthenticatedSuperadminRouteChildren: AuthenticatedSuperadminRouteChildren =
  {
    AuthenticatedSuperadminUsersRoute: AuthenticatedSuperadminUsersRoute,
    AuthenticatedSuperadminWorkspacesRoute:
      AuthenticatedSuperadminWorkspacesRoute,
    AuthenticatedSuperadminIndexRoute: AuthenticatedSuperadminIndexRoute,
  }

const AuthenticatedSuperadminRouteWithChildren =
  AuthenticatedSuperadminRoute._addFileChildren(
    AuthenticatedSuperadminRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBookingsRoute: typeof AuthenticatedBookingsRoute
  AuthenticatedFormsRoute: typeof AuthenticatedFormsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSelectOrganizationRoute: typeof AuthenticatedSelectOrganizationRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSuperadminRoute: typeof AuthenticatedSuperadminRouteWithChildren
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedFormFormIdEditRoute: typeof AuthenticatedFormFormIdEditRoute
  AuthenticatedTodosIdEditRoute: typeof AuthenticatedTodosIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBookingsRoute: AuthenticatedBookingsRoute,
  AuthenticatedFormsRoute: AuthenticatedFormsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSelectOrganizationRoute: AuthenticatedSelectOrganizationRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSuperadminRoute: AuthenticatedSuperadminRouteWithChildren,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedFormFormIdEditRoute: AuthenticatedFormFormIdEditRoute,
  AuthenticatedTodosIdEditRoute: AuthenticatedTodosIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthSigninRoute: AuthSigninRoute,
  BookFormIdRoute: BookFormIdRoute,
  InviteInvitationIdRoute: InviteInvitationIdRoute,
  Oauth2AccessCodeRoute: Oauth2AccessCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiHealthServerRoute: ApiHealthServerRoute,
  ApiAuthSplatServerRoute: ApiAuthSplatServerRoute,
  ApiAvatarsSplatServerRoute: ApiAvatarsSplatServerRoute,
  ApiAvatarsDeleteServerRoute: ApiAvatarsDeleteServerRoute,
  ApiAvatarsUploadServerRoute: ApiAvatarsUploadServerRoute,
  ApiStripeWebhookServerRoute: ApiStripeWebhookServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
